version: '2'

services:
  redis:
    restart: always
    image: docker.io/bitnami/redis:6.2
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      # - ALLOW_EMPTY_PASSWORD=yes
      # - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
      - REDIS_PASSWORD=redis123
    ports:
      - '6379:6379'

  # db:
  #   network_mode: default
  #   image: mysql:5.7
  #   # command: --default-authentication-plugin=mysql_native_password
  #   restart: always
  #   environment:
  #     MYSQL_ROOT_PASSWORD: Mysql123
  #   volumes: 
  #     - ./data:/var/lib/mysql
  #   ports:
  #     - 3306:3306

